Add kubernetes completion

diff --git a/templates/dev.env.sh.j2 b/templates/dev.env.sh.j2
--- a/templates/dev.env.sh.j2
+++ b/templates/dev.env.sh.j2
@@ -272,7 +272,11 @@ export CMAKE_ROOT=${CMAKE_HOME}
 # PYTHON {{PYTHON_MAJOR_VERSION}}
 #See run-python.sh script
 #export PYTHON_MAJOR_VERSION={{PYTHON_MAJOR_VERSION}}
-source ${HOME}/run-python.sh
+
+if [ -f ${HOME}/run-python.sh ]; then
+    echo ${HOME}/run-python.sh
+    source ${HOME}/run-python.sh
+fi
 
 #export PYTHON_DIR={{PYTHON_DIR}}
 #export VIRTUALENV_PATH=/opt/ansible/env$(echo $PYTHON_MAJOR_VERSION | sed -r 's/\.//g')
@@ -640,6 +644,11 @@ then
   export PATH=$PATH:${DRIVE_PATH}/Windows/system32:${DRIVE_PATH}/Windows
 fi
 
+# KUBERNETES
+source <(kubectl completion bash)
+alias k=kubectl
+complete -F __start_kubectl k
+
 ###
 # INCLUDE LANGUAGE SPECIFIC
 ###
@@ -849,7 +858,15 @@ export PAGER={{ PAGER }}
 export COWSAY="{{COWSAY}}/cowsay"
 if [ -f $COWSAY ]
 then
-  {{COWSAY}}/cowsay -f `ls /usr/share/cowsay/cows/ | rl | tail -n 1 | cut -d'.' -f1` "`/usr/games/fortune -s`"
+  command -v rl || {
+      echo -e "rl | randomize-lines not found in system PATH, please make sure that randomize-lines is installed"
+      echo -e "rl | apt-get install randomize-lines fortunes fortunes-fr"
+      #exit 1
+  }
+  if [ -f /usr/bin/rl ]
+  then  
+    {{COWSAY}}/cowsay -f `ls /usr/share/cowsay/cows/ | rl | tail -n 1 | cut -d'.' -f1` "`/usr/games/fortune -s`"
+  fi
 else
   echo -e "${red} ${double_arrow} Cowsay is not installed ${head_skull} ${NC}"
 fi
@@ -863,6 +880,17 @@ fi
 #fi
 
 export SHELLCHECK_OPTS="-e SC2154 -e SC2086"
+
+command -v docker || {
+	echo -e "Docker | docker not found in system PATH, please make sure that docker is installed"
+	echo -e "Docker | Recommended docker version is >= 18.09.9,"
+#	exit 1
+}
+command -v docker-compose || {
+	echo -e "Docker | docker-compose not found in system PATH, please make sure that docker-compose is installed"
+	echo -e "Docker | Recommended docker-compose version is >= 1.24.1"
+#	exit 1
+}
 
 source "${WORKING_DIR}/pass.env.sh"
 
